# Model arguments
model_name_or_path: /blue/yonghui.wu/sgao1/haoyan/spin-results/Llama-3-8B-Ultrachat-200K/SPIN/iter0
model_revision: main

dataset_mixer:
  /blue/yonghui.wu/sgao1/haoyan/gpt-preference-data-0/Llama-3-8B-Ultrachat-200K/trainable-noise: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.2
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 4
gradient_checkpointing: true
hub_model_id: zephyr-7b-spin
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 2
optim: rmsprop
output_dir: outputs
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1
save_only_model: true

