num_train_epochs = 3
bf16 = True
do_eval = False
evaluation_strategy = "no"
gradient_accumulation_steps = 1
gradient_checkpointing = True
log_level = "info"
logging_steps = 20
lr_scheduler_type = "linear"
learning_rate = 5.0e-07
overwrite_output_dir = True
per_device_eval_batch_size = 4
per_device_train_batch_size = 8
save_strategy = "epoch"
save_total_limit = 6
overwrite_output_dir = True
seed=42
save_only_model = True
