export CUDA_VISIBLE_DEVICES=0

source /home/user/miniconda3/etc/profile.d/conda.sh
conda activate spinenv


#### zephyr ####
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/models/zephyr-7b-sft-full --input_dir generated/zephyr-7b-sft-full/iter0/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/vanilla --split train --data_type real --sum_data_dir logprob_sum/zephyr-7b-sft-full/vanilla/log_prob_iter0_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/models/zephyr-7b-sft-full --input_dir generated/zephyr-7b-sft-full/iter0/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/vanilla --split train --data_type generated --sum_data_dir logprob_sum/zephyr-7b-sft-full/vanilla/log_prob_iter0_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter0-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter1/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter0 --split train --data_type real --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter0/log_prob_iter1_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter0-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter1/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter0 --split train --data_type generated --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter0/log_prob_iter1_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter1-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter2/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter1 --split train --data_type real --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter1-1step/log_prob_iter2_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter1-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter2/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter1 --split train --data_type generated --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter1-1step/log_prob_iter2_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter2-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter3/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter2 --split train --data_type real --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter2-1step/log_prob_iter3_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter2-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter3/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter2 --split train --data_type generated --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter2-1step/log_prob_iter3_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter3-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter4/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter3 --split train --data_type real --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter3-1step/log_prob_iter4_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter3-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter4/synthetic --output_dir logprob_avg_new/zephyr-7b-sft-full/iter3 --split train --data_type generated --sum_data_dir logprob_sum/zephyr-7b-sft-full/iter3-1step/log_prob_iter4_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter1-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter2/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter1-1step --split train --data_type real
# accelerate launch --num_processes 1 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter1-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter2/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter1-1step --split train --data_type generated

# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/reproduce_outputs/iter1-ckpt_iterative --input_dir generated/zephyr-7b-sft-full-reproduce/iter2/synthetic --output_dir logprob/zephyr-7b-sft-full/iter1-2steps --split train --data_type real
# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/reproduce_outputs/iter1-ckpt_iterative --input_dir generated/zephyr-7b-sft-full-reproduce/iter2/synthetic --output_dir logprob/zephyr-7b-sft-full/iter1-2steps --split train --data_type generated

# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter2-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter3/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter2-1step --split train --data_type real
# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter2-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter3/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter2-1step --split train --data_type generated

#### Llama ####
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model neuralmagic/Llama-2-7b-ultrachat200k --input_dir generated/Llama-2-7b-ultrachat200k/iter0/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/vanilla --split train --data_type real --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/vanilla/log_prob_iter0_real.npy
accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model neuralmagic/Llama-2-7b-ultrachat200k --input_dir generated/Llama-2-7b-ultrachat200k/iter0/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/vanilla --split train --data_type generated --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/vanilla/log_prob_iter0_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter0-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter1/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter0 --split train --data_type real --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter0/log_prob_iter1_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter0-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter1/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter0 --split train --data_type generated --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter0/log_prob_iter1_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter1-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter2/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter1-1step --split train --data_type real --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter1-1step/log_prob_iter2_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter1-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter2/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter1-1step --split train --data_type generated --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter1-1step/log_prob_iter2_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter2-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter3/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter2-1step --split train --data_type real --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter2-1step/log_prob_iter3_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter2-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter3/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter2-1step --split train --data_type generated --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter2-1step/log_prob_iter3_generated.npy

# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter3-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter4/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter3-1step --split train --data_type real --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter3-1step/log_prob_iter4_real.npy
# accelerate launch --num_processes 1 --main_process_port=2950 spin/convert_sum_to_average_KL.py --model /group-volume/haoyan/spin_results/Llama-2-7b-ultrachat200k/outputs/iter3-ckpt --input_dir generated/Llama-2-7b-ultrachat200k/iter4/synthetic --output_dir logprob_avg_new/Llama-2-7b-ultrachat200k/iter3-1step --split train --data_type generated --sum_data_dir logprob_sum/Llama-2-7b-ultrachat200k/iter3-1step/log_prob_iter4_generated.npy



# sft-generated
# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/sft_results/zephyr-7b-sft-full/outputs_generated/iter0/final --input_dir generated/zephyr-7b-sft-full-sft-generated/iter1/synthetic --output_dir logprob_sum/zephyr-7b-sft-full_sft_generated/iter0 --split train --data_type real
# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/sft_results/zephyr-7b-sft-full/outputs_generated/iter0/final --input_dir generated/zephyr-7b-sft-full-sft-generated/iter1/synthetic --output_dir logprob_sum/zephyr-7b-sft-full_sft_generated/iter0 --split train --data_type generated

# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/sft_results/Llama-2-7b-ultrachat200k/outputs_generated/iter0/final --input_dir generated/zephyr-7b-sft-full-new/iter3/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter2-1step --split train --data_type real
# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/sft_results/Llama-2-7b-ultrachat200k/outputs_generated/iter0/final --input_dir generated/zephyr-7b-sft-full-new/iter3/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter2-1step --split train --data_type generated

# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter3-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter4/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter3-1step --split train --data_type real
# accelerate launch --num_processes 4 --main_process_port=2950 spin/KL.py --model /group-volume/haoyan/spin_results/zephyr-7b-sft-full/new_outputs/iter3-ckpt --input_dir generated/zephyr-7b-sft-full-new/iter4/synthetic --output_dir logprob_sum/zephyr-7b-sft-full/iter3-1step --split train --data_type generated

